### PR TITLE
Add diffuse and direct irradiation and correct general term solarRadiation

### PR DESCRIPTION
**Pull request by IngMiad**
We have a weather station at our plant that measures weather observed. So far the FIWARE Smart Data Model WeatherObserved meets our data model besides the measures for radiation or irradiation.

Actually the model only contains solarRadiation measured in Watts per square. Our weather station differentiates between:
- Direct Irradiation: The direct radiation that reaches the earth's surface unimpeded by the direct path
- Diffuse Irradiation: The diffuse radiation that is scattered by the components of the atmosphere, e.g. clouds and dust
- Global irradiation: The sum of direct and diffuse radiation, or total solar irradiation

I think the measurement solarRadiation could mean global irradiation or overall irradiation. Therefore I'd like to:
1) extend the model with two further numbers for diffuse / direct irradiation
2) rename the variable solarRadiation to solarIrradiation (as this is what is being measured https://en.wikipedia.org/wiki/Solar_irradiance) or even globalIrradiation to describe exactly what is being measured here.

I look forward to discuss the changes and extension 😀

### CODE REVIEW

**Comment by albertoabellagarcia** [comment]
One comment: 
1) we will not remove the former attribute but you can add those ones in your PR. People will decide what to use depending on their use case.

In order to get your PR approved you have to 
1) Add an example in ngsi v2 or LD either normalized or key values format. 
2) Sign the [contribution agreement](https://smartdatamodels.org/index.php/contributor-agreement/). It is just a 3 fields form.
3) it is quite necessary that you can add an entry in the [ADOPTERS.yaml](https://github.com/smart-data-models/dataModel.Weather/blob/master/WeatherObserved/ADOPTERS.yaml) with data about your use case
4) If you want to appear as a contributor you can also add your data in the [CONTRIBUTORS.yaml](https://github.com/smart-data-models/dataModel.Weather/blob/master/CONTRIBUTORS.yaml)
Thanks for the contribution

**Comment by IngMiad** [comment]
Hello @albertoabellagarcia ,

Thank you for your reply. I can understand that renaming an attribute isn't possible, because changing an attribute name is kind of a breaking change for others that use attribute in their smart data model. 

Therefore I updated my PR and did following:
	1. Only add two further attributes (diffuseIrradiation, directIrradiation) and remove the change of "solarRadiation" 
	2. Leave the example as it is (there is already only a partial entity which doesn't contain solarRadiation as well)
	3. Signed the contribution
	4. Added myself to ADOPTERS.yaml
	5. Added myself to CONTRIBUTORS.yaml

Please don't hestiate to tell me if anything else is missing. 

Greetings
Inga

**Review by albertoabellagarcia — APPROVED** [review]
We'll appreciate if you can provide also an example of payload with value sfor these two new attributes

**Comment by albertoabellagarcia** [comment]
Merged

**Pull request merged**
